export default {
  'com.netflix.ninja': 'Netflix',
  'com.amazon.amazonvideo.livingroom': 'Amazon Prime Video',
  'com.google.android.youtube.tv': 'YouTube',
  'com.spotify.tv.android': 'Spotify',
  'com.disney.disneyplus': 'Disney+',
  'com.wbd.hbomax': 'HBO Max',
  'com.hulu.livingroomplus': 'Hulu',
  'com.apple.atve.androidtv.appletv': 'Apple TV',
  'org.videolan.vlc': 'VLC Media Player',
  'com.plexapp.android': 'Plex',
  'com.google.android.tvlauncher': 'Android TV Home (system)',
  'com.nvidia.geforcenow': 'NVIDIA GeForce NOW',
  'tv.twitch.android.app': 'Twitch',
  'com.tubitv': 'Tubi',
  'com.sling': 'Sling TV',
  'com.crunchyroll.crunchyroid': 'Crunchyroll',
  'org.xbmc.kodi': 'Kodi',
  'com.ionitech.airscreen': 'AirScreen',
  'tv.fubo.mobile': 'FuboTV',
  'com.cbs.ott': 'Paramount+',
  'com.discovery.dplay': 'Discovery+',
  'com.dazn': 'DAZN',
  'tv.arte.plus7': 'ARTE TV',
  'com.pbs.video': 'PBS',
  'com.google.android.tv': 'Google TV',
  'nl.rtl.videoland.v2': 'Videoland',
  'nl.uitzendinggemist': 'NPO Start',
  'com.ziggo.tv': 'Ziggo GO',
  'com.kpn.kpnandroidtv': 'KPN TV+',
  'com.android.tv.settings': 'Android TV settings (system)',
  'com.google.android.apps.tv.launcherx': 'Android TV launcher (system)',
  'com.android.vending': 'Google Play Store',
  'com.google.android.apps.tv.dreamx': 'Android TV screensaver (system)',
  'com.google.android.gms': 'Google Play Services (system)',
  'com.android.systemui': 'Android TV System UI (system)',
  'com.formulaone.production': 'F1 TV',
  'nl.nlziet': 'NLZIET',
} as Record<string, string>;
